//! Auto-generated rules imported from Rector
//!
//! Generated by rustor-import-rector

pub mod array_key_exists_on_property;
pub mod class_on_object;
pub mod consistent_implode;
pub mod filter_var_to_add_slashes;
pub mod get_class_on_null;
pub mod hebrevc_to_nl_2_br_hebrev;
pub mod inline_is_a_instance_of;
pub mod is_a_with_string_with_third_argument;
pub mod pow_to_exp;
pub mod preg_replace_e_modifier;
pub mod remove_get_class_get_parent_class_no_args;
pub mod remove_sole_value_sprintf;
pub mod remove_useless_is_object_check;
pub mod rename_mktime_without_args_to_time;
pub mod restore_include_path_to_ini_restore;
pub mod simplify_strpos_lower;
pub mod ternary_implode_to_implode;
pub mod unwrap_sprintf_one_argument;
pub mod utf_8_decode_encode_to_mb_convert_encoding;

use crate::registry::Rule;

/// Get all imported rules
pub fn imported_rules() -> Vec<Box<dyn Rule>> {
    vec![
        Box::new(array_key_exists_on_property::ArrayKeyExistsOnPropertyRule),
        Box::new(class_on_object::ClassOnObjectRule),
        Box::new(consistent_implode::ConsistentImplodeRule),
        Box::new(filter_var_to_add_slashes::FilterVarToAddSlashesRule),
        Box::new(get_class_on_null::GetClassOnNullRule),
        Box::new(hebrevc_to_nl_2_br_hebrev::HebrevcToNl2BrHebrevRule),
        Box::new(inline_is_a_instance_of::InlineIsAInstanceOfRule),
        Box::new(is_a_with_string_with_third_argument::IsAWithStringWithThirdArgumentRule),
        Box::new(pow_to_exp::PowToExpRule),
        Box::new(preg_replace_e_modifier::PregReplaceEModifierRule),
        Box::new(remove_get_class_get_parent_class_no_args::RemoveGetClassGetParentClassNoArgsRule),
        Box::new(remove_sole_value_sprintf::RemoveSoleValueSprintfRule),
        Box::new(remove_useless_is_object_check::RemoveUselessIsObjectCheckRule),
        Box::new(rename_mktime_without_args_to_time::RenameMktimeWithoutArgsToTimeRule),
        Box::new(restore_include_path_to_ini_restore::RestoreIncludePathToIniRestoreRule),
        Box::new(simplify_strpos_lower::SimplifyStrposLowerRule),
        Box::new(ternary_implode_to_implode::TernaryImplodeToImplodeRule),
        Box::new(unwrap_sprintf_one_argument::UnwrapSprintfOneArgumentRule),
        Box::new(utf_8_decode_encode_to_mb_convert_encoding::Utf8DecodeEncodeToMbConvertEncodingRule),
    ]
}
