# GitHub Action for Rustor
# Usage:
#   - uses: rustor/rustor-action@v1
#     with:
#       path: src/
#       preset: recommended
#       php-version: "8.2"

name: 'Rustor PHP Refactoring'
description: 'Analyze and modernize PHP code with rustor'
author: 'rustor contributors'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  path:
    description: 'Path to PHP files (default: current directory)'
    required: false
    default: '.'
  preset:
    description: 'Rule preset (recommended, performance, modernize, all)'
    required: false
    default: 'recommended'
  php-version:
    description: 'Target PHP version'
    required: false
    default: '8.2'
  rules:
    description: 'Comma-separated list of specific rules to enable'
    required: false
  format:
    description: 'Output format (text, json, sarif, github)'
    required: false
    default: 'github'
  fail-on-changes:
    description: 'Fail the action if changes are suggested'
    required: false
    default: 'true'
  only-changed:
    description: 'Only check files changed in the PR'
    required: false
    default: 'false'
  fix:
    description: 'Apply fixes automatically (creates commit)'
    required: false
    default: 'false'

outputs:
  files-changed:
    description: 'Number of files with suggested changes'
  total-edits:
    description: 'Total number of suggested edits'

runs:
  using: 'composite'
  steps:
    - name: Download Rustor
      shell: bash
      run: |
        RUSTOR_VERSION="0.2.0"
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        # Map architecture
        case "$ARCH" in
          x86_64) ARCH="x86_64" ;;
          aarch64|arm64) ARCH="aarch64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        # Download URL
        DOWNLOAD_URL="https://github.com/rustor/rustor/releases/download/v${RUSTOR_VERSION}/rustor-${OS}-${ARCH}"

        # Download and install
        curl -sL "$DOWNLOAD_URL" -o /tmp/rustor
        chmod +x /tmp/rustor
        sudo mv /tmp/rustor /usr/local/bin/rustor

        echo "Installed rustor v${RUSTOR_VERSION}"

    - name: Get changed files (PR only)
      id: changed-files
      if: inputs.only-changed == 'true' && github.event_name == 'pull_request'
      shell: bash
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep '\.php$' || true)
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run Rustor
      id: rustor
      shell: bash
      run: |
        ARGS="${{ inputs.path }}"
        ARGS="$ARGS --preset ${{ inputs.preset }}"
        ARGS="$ARGS --php-version ${{ inputs.php-version }}"
        ARGS="$ARGS --format ${{ inputs.format }}"

        if [ -n "${{ inputs.rules }}" ]; then
          IFS=',' read -ra RULES <<< "${{ inputs.rules }}"
          for rule in "${RULES[@]}"; do
            ARGS="$ARGS --rule $rule"
          done
        fi

        if [ "${{ inputs.fix }}" = "true" ]; then
          ARGS="$ARGS --fix"
        fi

        # Run rustor and capture output
        set +e
        OUTPUT=$(rustor $ARGS 2>&1)
        EXIT_CODE=$?
        set -e

        echo "$OUTPUT"

        # Parse summary if JSON format
        if [ "${{ inputs.format }}" = "json" ]; then
          FILES_CHANGED=$(echo "$OUTPUT" | jq -r '.summary.files_with_changes // 0')
          TOTAL_EDITS=$(echo "$OUTPUT" | jq -r '.summary.total_edits // 0')
        else
          FILES_CHANGED=$(echo "$OUTPUT" | grep -oP 'Files with changes: \K\d+' || echo "0")
          TOTAL_EDITS=$(echo "$OUTPUT" | grep -oP 'Total edits: \K\d+' || echo "0")
        fi

        echo "files-changed=$FILES_CHANGED" >> $GITHUB_OUTPUT
        echo "total-edits=$TOTAL_EDITS" >> $GITHUB_OUTPUT

        # Exit with error if changes found and fail-on-changes is true
        if [ "${{ inputs.fail-on-changes }}" = "true" ] && [ "$TOTAL_EDITS" -gt 0 ]; then
          echo "::error::Rustor found $TOTAL_EDITS suggested changes in $FILES_CHANGED files"
          exit 1
        fi

    - name: Create commit (if fix enabled)
      if: inputs.fix == 'true' && steps.rustor.outputs.total-edits > 0
      shell: bash
      run: |
        git config --local user.email "rustor[bot]@users.noreply.github.com"
        git config --local user.name "rustor[bot]"
        git add -A
        git commit -m "Apply rustor fixes

        Applied ${{ steps.rustor.outputs.total-edits }} changes across ${{ steps.rustor.outputs.files-changed }} files.

        Generated by rustor GitHub Action" || true
